"""Core enumerations for the bounded P003 ETEC research implementation."""
from enum import Enum


class TransitionClass(str, Enum):
    T1_EVENT_VERIFICATION = "T1_EVENT_VERIFICATION"
    T2_EXPOSURE = "T2_EXPOSURE"
    T3_DOMESTIC_TRANSMISSION = "T3_DOMESTIC_TRANSMISSION"
    T4_LOCAL_SCENARIO = "T4_LOCAL_SCENARIO"
    T5_MODEL_ESTIMATE_ELIGIBILITY = "T5_MODEL_ESTIMATE_ELIGIBILITY"
    T6_CALIBRATED_FORECAST = "T6_CALIBRATED_FORECAST"


class EdgeState(str, Enum):
    VERIFIED = "VERIFIED"
    SUPPORTED = "SUPPORTED"
    CONDITIONAL = "CONDITIONAL"
    CONTESTED = "CONTESTED"
    STALE = "STALE"
    INSUFFICIENT = "INSUFFICIENT"
    CONTRADICTED = "CONTRADICTED"


class OutputClass(str, Enum):
    ABSTAIN_INSUFFICIENT_EVIDENCE = "ABSTAIN_INSUFFICIENT_EVIDENCE"
    VERIFIED_EVENT_ONLY = "VERIFIED_EVENT_ONLY"
    EXPOSURE_IDENTIFIED = "EXPOSURE_IDENTIFIED"
    TRANSMISSION_SUPPORTED = "TRANSMISSION_SUPPORTED"
    MECHANISM_SUPPORTED_SCENARIO = "MECHANISM_SUPPORTED_SCENARIO"
    MODEL_ESTIMATE = "MODEL_ESTIMATE"
    CALIBRATED_FORECAST = "CALIBRATED_FORECAST"


class SourceAuthorityTier(int, Enum):
    OFFICIAL_PRIMARY = 1
    STATISTICAL_INSTITUTION = 2
    ACADEMIC = 3
    INDEPENDENT_REPORTING = 4
    SUPPLEMENTARY_INTELLIGENCE = 5
    MODEL_INFERENCE = 6
